import Head from "next/head";
import Image from "next/image";
import styles from "./Layout.module.css";
import Header from "./Header";

const Layout: React.FC = ({ children }): React.ReactElement => {
  return (
    <>
      <div className={styles.disclaimer}>
        <div>
          All transactions are submitted on the{" "}
          <a
            href="https://alfajores-blockscout.celo-testnet.org/"
            target="_blank"
            rel="noreferrer"
          >
            Alfajores Testnet
          </a>
          . <strong>Not real money will ever be exchanged</strong>.{" "}
          <a
            href="https://celo.org/developers/faucet"
            target="_blank"
            rel="noreferrer"
          >
            Top-up your account here
          </a>
        </div>
      </div>
      <div className={styles.container}>
        <Head>
          <title>Celo Connect 2022</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Header />
        {children}

        <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{" "}
            <span className={styles.logo}>
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                width={72}
                height={16}
              />
            </span>
          </a>
        </footer>
      </div>
    </>
  );
}

export default Layout;
