import "../styles/globals.css";
import "@celo-tools/use-contractkit/lib/styles.css";
import type { AppProps } from "next/app";
import Head from "next/head";
import Image from "next/image";
import styles from "./Home.module.css";
import { Alfajores, ContractKitProvider } from "@celo-tools/use-contractkit";
import Header from "../components/Header";
import { useCallback, useEffect, useState } from "react";

function MyApp({ Component, pageProps }: AppProps) {
  const [showDisclaimer, setShowDisclaimer] = useState(true);

  const hideDisclaimer = useCallback(() => {
    setShowDisclaimer(false);
    localStorage.setItem("alfajores-disclaimer", "hidden");
  }, []);

  useEffect(() => {
    if (localStorage.getItem("alfajores-disclaimer") === "hidden") {
      setShowDisclaimer(false);
    }
  }, []);

  return (
    <ContractKitProvider
      dapp={{
        name: "Celo Connect Dapp",
        description: "My first dapp",
        url: "https://celoconnect.com/",
        icon: "https://celoconnect.com/wp-content/uploads/2022/02/cc-full-final.svg",
      }}
      network={Alfajores}
    >
      {showDisclaimer && (
        <div className={styles.disclaimer}>
          <div>
            All transactions are submitted on the{" "}
            <a
              href="https://alfajores-blockscout.celo-testnet.org/"
              target="_blank"
              rel="noreferrer"
            >
              Alfajores Testnet
            </a>
            . <strong>Not real money will ever be exchanged</strong>.{" "}
            <a
              href="https://celo.org/developers/faucet"
              target="_blank"
              rel="noreferrer"
            >
              Top-up your account here
            </a>
          </div>
          <button onClick={hideDisclaimer}>Hide this message</button>
        </div>
      )}
      <div className={styles.container}>
        <Head>
          <title>Celo Connect 2022</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Header />
        <Component {...pageProps} />

        <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{" "}
            <span className={styles.logo}>
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                width={72}
                height={16}
              />
            </span>
          </a>
        </footer>
      </div>
    </ContractKitProvider>
  );
}

export default MyApp;
